# SPDX-License-Identifier: GPL-2.0
dtb-y += mt6765.dtb
dtb-$(CONFIG_HQ_PROJECT_HS04) += mt6765_a04e_eur_open_00.dtb
dtb-$(CONFIG_HQ_PROJECT_HS03S) += mt6765_a03s_eur_open_00.dtb

always            := $(dtb-y)
clean-files       := *.dtb*
